name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.actor }}
    steps:
      - run: echo "{$ACTOR}" #refer to context through Intermediate environmen variables